"""create businesses table

Revision ID: 30a7921b1726
Revises: da2cc6ebd053
Create Date: 2026-08-18 10:07:14.376945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a7921b1726'
down_revision = 'da2cc6ebd053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('working_hours', sa.Text(), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))
        batch_op.drop_index(batch_op.f('ix_businesses_is_active'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
