"""add first and last name to users

Revision ID: 46719847d31d
Revises: a499319d22c6
Create Date: 2026-09-09 20:07:53.758311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46719847d31d'
down_revision = 'a499319d22c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
