"""add subscription status

Revision ID: 6d732c62ea10
Revises: 8afc428ca87b
Create Date: 2026-09-13 19:28:31.173104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d732c62ea10'
down_revision = '8afc428ca87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=30),
                nullable=False,
                server_default='active'
            )
        )

        batch_op.create_index(
            batch_op.f('ix_subscriptions_status'),
            ['status'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_subscriptions_status')
        )

        batch_op.drop_column('status')

    # ### end Alembic commands ###