"""add plan options

Revision ID: 8afc428ca87b
Revises: e54a0c860b9c
Create Date: 2026-09-13 18:00:21.392958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afc428ca87b'
down_revision = 'e54a0c860b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_options_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_options_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_options_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_options_is_active'))

    op.drop_table('plan_options')
    # ### end Alembic commands ###
