"""add payment receipt fields to subscriptions

Revision ID: 95e9e4276b28
Revises: 708bcfe3a2dc
Create Date: 2026-09-13 20:19:32.477523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e9e4276b28'
down_revision = '708bcfe3a2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_receipt', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_tracking_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_submitted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('payment_submitted_at')
        batch_op.drop_column('payment_description')
        batch_op.drop_column('payment_tracking_code')
        batch_op.drop_column('payment_receipt')

    # ### end Alembic commands ###
