"""add password reset requests

Revision ID: a73f9621627e
Revises: 4dc4a55fea76
Create Date: 2026-09-19 10:21:33.121285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73f9621627e'
down_revision = '4dc4a55fea76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_status'))

    op.drop_table('password_reset_requests')
    # ### end Alembic commands ###
