"""allow multiple businesses per user

Revision ID: ac50b70f145e
Revises: 9506f9696d6a
Create Date: 2026-08-31 16:26:20.623580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac50b70f145e'
down_revision = '9506f9696d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=1)

    # ### end Alembic commands ###
